In [82]:
import numpy as np

In [83]:
array = np.array([[1,2,3],
                 [2,3,4]])            #列表转换为矩阵

print(array)
print('number of the dim:',array.ndim)#数组维度
print('shape:',array.shape)#行、列情况
print('size:',array.size)#元素个数

[[1 2 3]
 [2 3 4]]
number of the dim: 2
shape: (2, 3)
size: 6


In [84]:
a = np.array([1,23,4],dtype=np.int64)     #创建一个 array,指定它的类型
print(a.dtype)

b = np.array([[1,23,45],
              [43,4,76]])
print(b)

c = np.zeros((3,4))#生成指定行列的全零元素的数组
print(c)

d = np.ones((3,4),dtype = np.int16)# 全一数组
print(d)

e = np.empty((3,4))
print(e)

f = np.arange(10,20,2)#  生成一个步长为2的一维数组 [10,20)
print(f)

g = np.arange(12).reshape((3,4)) #将一维数组变形
print(g)

f = np.linspace(1,10,6).reshape((2,3))#生成线段 从数值1到10，分成5等份并更改形状
print(f)

int64
[[ 1 23 45]
 [43  4 76]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


In [141]:
#numpy基础运算
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
h = np.array([[1,1],
              [0,1]])
f = np.arange(4).reshape((2,2))

c = a-b 
print(a,b)
print(b**2)#求平方
print(c)

d = 10*np.sin(b)#输入参数为弧度制
print(d)

print(b<3)
print(b==3)

#矩阵乘法（内积）VS矩阵叉乘——对应元素相乘
g = h*f
g_dot = np.dot(f,h)
g_dot2 = f.dot(h)
print(g)
print(g_dot)
print(g_dot2)

k = np.random.random((2,4)) #random模块下的的random方法 随机生成0——1的数字
print(k)
print('******')
print(np.sum(k,axis=1))#axis=0表示对行（上下）进行操作  axis=1 表示对列（左右）进行操作
print('******')
print(np.max(k,axis=0))
print('******')
print(np.min(k,axis=1))
print('******')

A = np.arange(2,14).reshape((3,4))
print(np.argmin(A))#最小值的索引
print(np.argmax(A))

print(np.mean(A))#平均值
print(np.mean(A,axis=0))# 可指定行列进行运算
print(np.median(A))#中位数
print(A)
print(np.cumsum(A))#第一个值 第一个值加第二个值 第一个加第二个加第三个值.....累加
print(np.diff(A))#累减 第二个减第一个......
print(np.nonzero(A))#输出非零值的索引

B = np.arange(14,2,-1).reshape((3,4))# +、-表示方向 后续数字表示步长
print(B)
print(np.sort(B))#逐行升序排序

print(np.transpose(B))#矩阵转置OR  print(A.T)
print((A.T).dot(A))

print(np.clip(A,5,9))#过滤 对矩阵中值小于5改变为5或大于9改变为 9 


[10 20 30 40] [0 1 2 3]
[0 1 4 9]
[10 19 28 37]
[0.         8.41470985 9.09297427 1.41120008]
[ True  True  True False]
[False False False  True]
[[0 1]
 [0 3]]
[[0 1]
 [2 5]]
[[0 1]
 [2 5]]
[[0.36727358 0.72605956 0.03726021 0.09561376]
 [0.24434343 0.51873392 0.35550451 0.29231057]]
******
[1.22620711 1.41089243]
******
[0.36727358 0.72605956 0.35550451 0.29231057]
******
[0.03726021 0.24434343]
******
0
11
7.5
7.5
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]


In [155]:
import numpy as np #索引

A = np.arange(3,15).reshape((3,4))
print(A[2][1])
print(A[2,1])
print(A[1,:])#类似列表的切片
print('******')

print(A)
for row in A :
    print(row)

for column in A.T:
    print(column)

print(A)
print(A.flatten())
for item in A.flat:
    print(item)


12
12
[ 7  8  9 10]
******
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [187]:
#numpy与 array的合并
import numpy as np
A = np.array([1,1,1])#A\B均为序列
B = np.array([2,2,2])

C = np.vstack((A,B))  #vertival stack
D = np.hstack((A,B)) #horizontal stack
print(A.shape,C.shape)#(3,) 3行0列
print(D) #仍然是序列
print(D.shape)

print(A.shape)
print(A[np.newaxis,:].shape)#行上面增加一个维度
print(A[:,np.newaxis].shape)#列上增加一个维度


A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
E = np.hstack((A,B))
print(E)
print(E.shape)

R = np.concatenate((A,B,A,B),axis=0)#指定维度 将多个序列进行合并 axis=0 /1每个 array在上下/ 左右维度进行合并
print(R)



(3,) (2, 3)
[1 1 1 2 2 2]
(6,)
(3,)
(1, 3)
(3, 1)
[[1 2]
 [1 2]
 [1 2]]
(3, 2)
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]]


In [197]:
#array的分割
import numpy as np
A = np.arange(12).reshape((3,4))

print(A)
print(np.split(A,2,axis=1))#A分成两部分  axis=1  第二维度上进行切割相当于对每一行进行切分

print(np.array_split(A,3,axis=1))#进行不等分割

print(np.vsplit(A,3))
print(np.hsplit(A,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [201]:
#numpy copy/deepcopy
import numpy as np

a = np.arange(4)
b = a
c = a.copy()
a[0] = 55
print(a,b,c)




[55  1  2  3] [55  1  2  3] [0 1 2 3]
